name: Docker Python Build

on:
  #  push:
  #    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image (no push)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: docker-test-python:latest

    - name: Run container
      run: |
        docker run -d --rm --name schedule-test -p 8000:8000 docker-test-python:latest

    - name: Wait for Webserver to become healthy
      run: |
        curl --fail --silent --show-error \
             --retry 15 --retry-delay 2 --retry-connrefused \
             http://localhost:8000/healthcheck

    - name: Test Webserver
      run: |
        curl -f http://localhost:8000/healthcheck

    - name: Show container logs on failure
      if: failure()
      run: |
        docker logs schedule-test || true

    - name: Stop container
      if: always()
      run: |
        docker stop schedule-test || true
