name: Docker build and DockerHub push
on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_REPOSITORY }}
          tags: |
            type=raw,value=latest

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run container
        run: |
          docker run -d --rm --name schedule-test -p 8000:8000 ${{ steps.meta.outputs.tags }}

      - name: Wait for Webserver to become healthy
        run: |
          curl -fsS --retry 30 --retry-delay 1 --retry-all-errors \
              http://localhost:8000/healthcheck \
              && echo "Webserver is healthy" || echo "Webserver did not become healthy in time"

      - name: Test Webserver
        run: |
          curl -f http://localhost:8000/healthcheck

      - name: Show container logs on failure
        if: failure()
        run: |
          docker logs schedule-test || true

      - name: Stop container
        if: always()
        run: |
          docker stop schedule-test || true

      - name: Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
