name: Test Python Webserver

on:
  #  push:
  #    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.12
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
            cache: 'pip'
            cache-dependency-path: requirements.txt

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Start Webserver in Background
          run: |
            nohup python webserver.py > webserver.log 2>&1 & echo $! > server.pid

        - name: Wait for Webserver to become healthy
          run: |
            curl --fail --silent --show-error \
                 --retry 15 --retry-delay 2 --retry-connrefused \
                 http://localhost:8000/healthcheck

        - name: Test Webserver
          run: |
            curl -f http://localhost:8000/healthcheck

        - name: Show server logs on failure
          if: failure()
          run: |
            echo "--- webserver.log (tail) ---" && tail -n 200 webserver.log || true

        - name: Stop Webserver
          if: always()
          run: |
            if [ -f server.pid ]; then kill $(cat server.pid) || true; fi
